const fs = require('fs');
const path = require('path');

// ============================================================
// Table/view definitions — loaded from JSON or CLI args
// Usage: node generate_stored_procedures.js [tables.json] [output_dir] [views.json]
// ============================================================
const isMain = require.main === module;

let tables;
if (isMain && process.argv[2]) {
  tables = require(path.resolve(process.argv[2]));
} else {
  tables = require('./generate_tables');
}

// ============================================================
// Helpers
// ============================================================

function toPascalCase(snake) {
  return snake.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function getAllColumns(table) {
  const cols = [`${table.name}_id`, ...table.columns.map(c => c.name)];
  if (!table.skipModified) cols.push('modified');
  cols.push('created');
  return cols;
}

function pkParam(table) {
  return `@p_${toPascalCase(table.name)}RecordId`;
}

function colParam(col) {
  return `@p_${toPascalCase(col.name)}`;
}

// ============================================================
// View helpers
// ============================================================

function getViewColumns(view) {
  const cols = [`${view.baseTable}_id`];
  for (const c of view.baseCols) cols.push(c);
  for (const join of view.joins) {
    for (const c of join.cols) {
      cols.push(typeof c === 'string' ? c : c.as);
    }
  }
  const audit = view.auditCols || ['modified', 'created'];
  for (const c of audit) cols.push(c);
  return cols;
}

// ============================================================
// sx_get_
// ============================================================

function generateGet(table) {
  const name = table.name;
  const pk = pkParam(table);
  const spName = `sx_get_${name}`;
  const cols = getAllColumns(table);
  const selectList = cols.map(c => `        ${c}`).join(',\n');
  const hasIsActive = table.columns.some(c => c.name === 'is_active');
  const includeInactiveParam = hasIsActive ? `,\n    @p_IncludeInactive BIT = 0` : '';
  const includeInactiveDoc = hasIsActive ? `\n    @p_IncludeInactive BIT = 0 - If 1, include inactive records` : '';
  const activeFilter = hasIsActive ? `\n        AND (is_active = 1 OR @p_IncludeInactive = 1)` : '';

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Retrieves a single ${name} record by primary key
Author: Generated
Created: 2026-02-22

Parameters:
    ${pk} UNIQUEIDENTIFIER - The ${name} primary key${includeInactiveDoc}

Returns:
    Single row result set or empty if not found
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
    ${pk} UNIQUEIDENTIFIER${includeInactiveParam}
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
${selectList}
    FROM ${name}
    WHERE ${name}_id = ${pk}${activeFilter};

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_list_
// ============================================================

function generateList(table) {
  const name = table.name;
  const spName = `sx_list_${name}`;
  const cols = getAllColumns(table);
  const selectList = cols.map(c => `        ${c}`).join(',\n');

  // Build whitelist of sortable column names
  const sortableCols = cols.map(c => `'${c}'`).join(', ');

  // Build IF/ELSE IF branches for each column + direction combo
  const branches = [];
  for (const col of cols) {
    for (const dir of ['ASC', 'DESC']) {
      branches.push(`    ${branches.length === 0 ? 'IF' : 'ELSE IF'} @p_SortBy = '${col}' AND @p_SortDirection = '${dir}'
        SELECT
${selectList}
        FROM ${name}
        ORDER BY ${col} ${dir}
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);
    }
  }
  // Default fallback
  branches.push(`    ELSE
        SELECT
${selectList}
        FROM ${name}
        ORDER BY created DESC
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Retrieves a paged list of ${name} records
Author: Generated
Created: 2026-02-22

Parameters:
    @p_PageNumber INT = 1 - Page number (1-based)
    @p_PageSize INT = 50 - Number of records per page
    @p_SortBy NVARCHAR(50) = 'created' - Column name to sort by
    @p_SortDirection NVARCHAR(4) = 'DESC' - Sort direction (ASC or DESC)
    @o_RecordCount INT OUTPUT - Total number of matching records

Returns:
    Paged result set with sort and direction applied
    @o_RecordCount contains total matching records for paging UI
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
    @p_PageNumber INT = 1,
    @p_PageSize INT = 50,
    @p_SortBy NVARCHAR(50) = 'created',
    @p_SortDirection NVARCHAR(4) = 'DESC',
    @o_RecordCount INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    -- Validate sort parameters
    IF @p_SortBy NOT IN (${sortableCols})
        SET @p_SortBy = 'created';

    IF @p_SortDirection NOT IN ('ASC', 'DESC')
        SET @p_SortDirection = 'DESC';

    -- Total count
    SELECT @o_RecordCount = COUNT(*)
    FROM ${name};

    -- Paged results (static ORDER BY per column to allow index usage)
${branches.join('\n')}

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_upsert_
// ============================================================

function generateUpsert(table) {
  const name = table.name;
  const pk = pkParam(table);
  const spName = `sx_upsert_${name}`;
  const cols = table.columns;

  // -- Parameter list --
  const params = [];
  params.push(`    ${pk} UNIQUEIDENTIFIER = NULL`);

  const bitmaskDocs = [];
  const needsBigint = cols.length > 31;
  cols.forEach((col, i) => {
    params.push(`    ${colParam(col)} ${col.type.toUpperCase()} = NULL`);
    bitmaskDocs.push(`        ${String(1n << BigInt(i))} = ${col.name}`);
  });

  params.push(`    @p_UpdateFields ${needsBigint ? 'BIGINT' : 'INT'} = 0`);
  params.push(`    @o_IsSuccess BIT OUTPUT`);
  params.push(`    @o_ErrorMessage NVARCHAR(255) OUTPUT`);
  params.push(`    @o_NewRecordId UNIQUEIDENTIFIER OUTPUT`);

  // -- Required field validation (NOT NULL, no default) --
  const requiredCols = cols.filter(c => !c.nullable && !c.default);
  let insertValidation = '';
  for (const col of requiredCols) {
    const p = colParam(col);
    insertValidation += `
            IF ${p} IS NULL
            BEGIN
                SET @o_ErrorMessage = '${col.name} is required';
                ROLLBACK TRANSACTION;
                RETURN -1;
            END
`;
  }

  // -- Natural key lookup (when pk is NULL, find existing by natural key) --
  let naturalKeyLookup = '';
  if (table.naturalKey && table.naturalKey.length > 0) {
    const nkCols = table.naturalKey;
    const nkConditions = nkCols.map(nk => {
      const col = cols.find(c => c.name === nk);
      const p = colParam(col);
      if (col.nullable) {
        return `(${nk} = ${p} OR (${nk} IS NULL AND ${p} IS NULL))`;
      }
      return `${nk} = ${p}`;
    }).join('\n                AND ');

    // Build the all-fields bitmask for natural key match (all non-key columns)
    const allFieldsBitmask = cols.reduce((mask, col, i) => {
      if (!nkCols.includes(col.name)) {
        return mask | (1n << BigInt(i));
      }
      return mask;
    }, 0n);

    naturalKeyLookup = `
        -- Natural key lookup: check if record already exists
        IF ${pk} IS NULL
        BEGIN
            SELECT ${pk} = ${name}_id
            FROM ${name}
            WHERE ${nkConditions};

            IF ${pk} IS NOT NULL
            BEGIN
                SET @o_NewRecordId = ${pk};
                -- Set update bitmask to all non-key fields if caller didn't specify
                IF @p_UpdateFields = 0
                    SET @p_UpdateFields = ${needsBigint ? `CAST(${allFieldsBitmask} AS BIGINT)` : allFieldsBitmask};
            END
        END
`;
  }

  // -- INSERT columns and values --
  const insertCols = cols.map(c => c.name);
  const insertVals = cols.map(col => {
    const p = colParam(col);
    if (col.default) {
      return `ISNULL(${p}, ${col.default})`;
    }
    return p;
  });

  const insertColStr = insertCols.map(c => `                ${c}`).join(',\n');
  const insertValStr = insertVals.map(v => `                ${v}`).join(',\n');

  // -- UPDATE SET clause with bitmask --
  const updateSets = [];
  cols.forEach((col, i) => {
    const bitVal = String(1n << BigInt(i));
    const bit = needsBigint ? `CAST(${bitVal} AS BIGINT)` : bitVal;
    const p = colParam(col);
    updateSets.push(`                ${col.name} = CASE WHEN (@p_UpdateFields & ${bit}) = ${bit} THEN ${p} ELSE ${col.name} END`);
  });

  // -- Change detection: skip UPDATE if all bitmask fields already match --
  const changeChecks = [];
  cols.forEach((col, i) => {
    const bitVal = String(1n << BigInt(i));
    const bit = needsBigint ? `CAST(${bitVal} AS BIGINT)` : bitVal;
    const p = colParam(col);
    changeChecks.push(`                AND ((@p_UpdateFields & ${bit}) = 0 OR ${col.name} = ${p} OR (${col.name} IS NULL AND ${p} IS NULL))`);
  });

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Inserts or updates a ${name} record
Author: Generated
Created: 2026-02-22

Parameters:
    ${pk} UNIQUEIDENTIFIER = NULL - NULL for insert, existing ID for update
    @p_UpdateFields ${needsBigint ? 'BIGINT' : 'INT'} = 0 - Bitmask for selective updates:
${bitmaskDocs.join('\n')}
    @o_IsSuccess BIT OUTPUT - 1 if succeeded, 0 if failed
    @o_ErrorMessage NVARCHAR(255) OUTPUT - Error description if failed
    @o_NewRecordId UNIQUEIDENTIFIER OUTPUT - The record ID (new or existing)

Returns:
    0 on success, -1 on failure
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
${params.join(',\n')}
AS
BEGIN
    SET NOCOUNT ON;

    -- Initialize output parameters
    SET @o_IsSuccess = 0;
    SET @o_ErrorMessage = '';
    SET @o_NewRecordId = ${pk};
${naturalKeyLookup}
    BEGIN TRY
        BEGIN TRANSACTION;

        IF ${pk} IS NULL
        BEGIN
            -- INSERT
${insertValidation}
            DECLARE @InsertedIds TABLE (id UNIQUEIDENTIFIER);

            INSERT INTO ${name} (
${insertColStr}
            )
            OUTPUT INSERTED.${name}_id INTO @InsertedIds
            VALUES (
${insertValStr}
            );

            SELECT @o_NewRecordId = id FROM @InsertedIds;
        END
        ELSE
        BEGIN
            -- UPDATE (only if at least one field has actually changed)
            IF NOT EXISTS (SELECT 1 FROM ${name} WHERE ${name}_id = ${pk})
            BEGIN
                SET @o_ErrorMessage = '${name} not found';
                ROLLBACK TRANSACTION;
                RETURN -1;
            END

            -- Skip update if all included fields already match (prevents unnecessary history)
            IF NOT EXISTS (
                SELECT 1 FROM ${name}
                WHERE ${name}_id = ${pk}
${changeChecks.join('\n')}
            )
            BEGIN
                UPDATE ${name}
                SET
${updateSets.join(',\n')}
                WHERE ${name}_id = ${pk};
            END
        END

        COMMIT TRANSACTION;
        SET @o_IsSuccess = 1;
        RETURN 0;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        SET @o_ErrorMessage = ERROR_MESSAGE();
        SET @o_IsSuccess = 0;
        RETURN -1;
    END CATCH

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_delete_ (soft delete — sets is_active = 0)
// ============================================================

function generateDelete(table, allTables) {
  const name = table.name;
  const pk = pkParam(table);
  const spName = `sx_delete_${name}`;

  // Find tables that reference this table via FK
  const dependents = [];
  for (const other of allTables) {
    if (other.name === name) continue;
    for (const fk of other.fks) {
      if (fk.refTable === name) {
        const hasIsActive = other.columns.some(c => c.name === 'is_active');
        dependents.push({ table: other.name, col: fk.col, hasIsActive });
      }
    }
  }

  let dependencyChecks = '';
  for (const dep of dependents) {
    const condition = dep.hasIsActive
      ? `SELECT 1 FROM ${dep.table} WHERE ${dep.col} = ${pk} AND is_active = 1`
      : `SELECT 1 FROM ${dep.table} WHERE ${dep.col} = ${pk}`;
    dependencyChecks += `
        IF EXISTS (${condition})
        BEGIN
            SET @o_ErrorMessage = 'Cannot deactivate ${name}: active ${dep.table} records exist';
            RETURN -1;
        END
`;
  }

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Soft-deletes a ${name} record by setting is_active = 0
Author: Generated
Created: 2026-02-22

Parameters:
    ${pk} UNIQUEIDENTIFIER - The ${name} primary key
    @o_IsSuccess BIT OUTPUT - 1 if succeeded, 0 if failed
    @o_ErrorMessage NVARCHAR(255) OUTPUT - Error description if failed

Returns:
    0 on success, -1 on failure
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
    ${pk} UNIQUEIDENTIFIER,
    @o_IsSuccess BIT OUTPUT,
    @o_ErrorMessage NVARCHAR(255) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    SET @o_IsSuccess = 0;
    SET @o_ErrorMessage = '';

    IF NOT EXISTS (SELECT 1 FROM ${name} WHERE ${name}_id = ${pk} AND is_active = 1)
    BEGIN
        SET @o_ErrorMessage = '${name} not found or already inactive';
        RETURN -1;
    END
${dependencyChecks}
    UPDATE ${name}
    SET is_active = 0
    WHERE ${name}_id = ${pk};

    SET @o_IsSuccess = 1;
    RETURN 0;

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_list_*_history
// ============================================================

function generateListHistory(table) {
  const name = table.name;
  const pk = pkParam(table);
  const spName = `sx_list_${name}_history`;
  const cols = getAllColumns(table);
  const selectList = [
    `        ${name}_history_id`,
    ...cols.map(c => `        ${c}`),
    '        archived_at',
  ].join(',\n');

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Retrieves history records for a specific ${name} row
Author: Generated
Created: 2026-02-22

Parameters:
    ${pk} UNIQUEIDENTIFIER - The ${name} primary key to get history for

Returns:
    All archived versions of the record, most recent first
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
    ${pk} UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
${selectList}
    FROM history.${name}
    WHERE ${name}_id = ${pk}
    ORDER BY archived_at DESC;

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_get_{view_name} — get from view by base table PK
// ============================================================

function generateViewGet(view) {
  const vName = `vx_${view.name}`;
  const spName = `sx_get_${view.name}`;
  const pkCol = `${view.baseTable}_id`;
  const pk = `@p_${toPascalCase(view.baseTable)}RecordId`;
  const cols = getViewColumns(view);
  const selectList = cols.map(c => `        ${c}`).join(',\n');

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Retrieves a single ${view.baseTable} record with related data from ${vName}
Author: Generated
Created: 2026-02-22

Parameters:
    ${pk} UNIQUEIDENTIFIER - The ${view.baseTable} primary key

Returns:
    Single row result set with denormalized data or empty if not found
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
    ${pk} UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
${selectList}
    FROM ${vName}
    WHERE ${pkCol} = ${pk};

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// sx_list_{view_name} — paged list from view
// ============================================================

function generateViewList(view) {
  const vName = `vx_${view.name}`;
  const spName = `sx_list_${view.name}`;
  const cols = getViewColumns(view);
  const selectList = cols.map(c => `        ${c}`).join(',\n');
  const sortableCols = cols.map(c => `'${c}'`).join(', ');
  const hasIsActive = cols.includes('is_active');

  const includeInactiveParam = hasIsActive ? `    @p_IncludeInactive BIT = 0,\n` : '';
  const includeInactiveDoc = hasIsActive ? `    @p_IncludeInactive BIT = 0 - If 1, include inactive records\n` : '';
  const activeFilter = hasIsActive ? `\n    WHERE (is_active = 1 OR @p_IncludeInactive = 1)` : '';
  const activeWhere = hasIsActive ? `\n        WHERE (is_active = 1 OR @p_IncludeInactive = 1)` : '';

  // Build IF/ELSE IF branches for each column + direction combo
  const branches = [];
  for (const col of cols) {
    for (const dir of ['ASC', 'DESC']) {
      branches.push(`    ${branches.length === 0 ? 'IF' : 'ELSE IF'} @p_SortBy = '${col}' AND @p_SortDirection = '${dir}'
        SELECT
${selectList}
        FROM ${vName}${activeWhere}
        ORDER BY ${col} ${dir}
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);
    }
  }
  // Default fallback
  branches.push(`    ELSE
        SELECT
${selectList}
        FROM ${vName}${activeWhere}
        ORDER BY created DESC
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: Retrieves a paged list from ${vName} with denormalized data
Author: Generated
Created: 2026-02-22

Parameters:
${includeInactiveDoc}    @p_PageNumber INT = 1 - Page number (1-based)
    @p_PageSize INT = 50 - Number of records per page
    @p_SortBy NVARCHAR(50) = 'created' - Column name to sort by
    @p_SortDirection NVARCHAR(4) = 'DESC' - Sort direction (ASC or DESC)
    @o_RecordCount INT OUTPUT - Total number of matching records

Returns:
    Paged result set with sort and direction applied
    @o_RecordCount contains total matching records for paging UI
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
${includeInactiveParam}    @p_PageNumber INT = 1,
    @p_PageSize INT = 50,
    @p_SortBy NVARCHAR(50) = 'created',
    @p_SortDirection NVARCHAR(4) = 'DESC',
    @o_RecordCount INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    -- Validate sort parameters
    IF @p_SortBy NOT IN (${sortableCols})
        SET @p_SortBy = 'created';

    IF @p_SortDirection NOT IN ('ASC', 'DESC')
        SET @p_SortDirection = 'DESC';

    -- Total count
    SELECT @o_RecordCount = COUNT(*)
    FROM ${vName}${activeFilter};

    -- Paged results (static ORDER BY per column to allow index usage)
${branches.join('\n')}

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// Write files
// ============================================================

if (require.main === module) {
  const outputBase = process.argv[3] ? path.resolve(process.argv[3]) : __dirname;
  const viewsJsonPath = process.argv[4] ? path.resolve(process.argv[4]) : null;
  const views = viewsJsonPath ? require(viewsJsonPath) : [];

  const SP_DIR = path.join(outputBase, 'STORED_PROCEDURES');

  if (!fs.existsSync(SP_DIR)) {
    fs.mkdirSync(SP_DIR, { recursive: true });
  }

  let count = 0;

  // Table SPs
  for (const table of tables) {
    const sps = [
      [`sx_get_${table.name}`, generateGet(table)],
      [`sx_list_${table.name}`, generateList(table)],
      [`sx_upsert_${table.name}`, generateUpsert(table)],
    ];

    const hasIsActive = table.columns.some(c => c.name === 'is_active');
    if (hasIsActive) {
      sps.push([`sx_delete_${table.name}`, generateDelete(table, tables)]);
    }

    if (table.hasHistory) {
      sps.push([`sx_list_${table.name}_history`, generateListHistory(table)]);
    }

    for (const [spName, sql] of sps) {
      fs.writeFileSync(path.join(SP_DIR, `${spName}.sql`), sql, 'utf8');
      count++;
    }
  }

  // View SPs
  for (const view of views) {
    const sps = [
      [`sx_get_${view.name}`, generateViewGet(view)],
      [`sx_list_${view.name}`, generateViewList(view)],
    ];

    for (const [spName, sql] of sps) {
      fs.writeFileSync(path.join(SP_DIR, `${spName}.sql`), sql, 'utf8');
      count++;
    }
  }

  // sx_test — connection diagnostic procedure
  const testSql = `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'sx_test')
    DROP PROCEDURE sx_test;
GO

CREATE PROCEDURE sx_test
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        'pass' [test],
        encrypt_option [encryption],
        auth_scheme [auth_scheme]
    FROM sys.dm_exec_connections
    WHERE session_id = @@SPID;
END;
GO
`;
  fs.writeFileSync(path.join(SP_DIR, 'sx_test.sql'), testSql, 'utf8');
  count++;

  console.log(`Generated ${count} stored procedure files in ${SP_DIR}`);
}

module.exports = tables;
