const fs = require('fs');
const path = require('path');

// ============================================================
// Usage: node generate_stored_procedures_by.js [sp_by.json] [output_dir] [tables.json]
// ============================================================
const isMain = require.main === module;

const spByJsonPath = (isMain && process.argv[2])
  ? path.resolve(process.argv[2])
  : path.join(__dirname, 'stored_procedures_by.json');
const spByData = require(spByJsonPath);

let tables;
if (isMain && process.argv[4]) {
  tables = require(path.resolve(process.argv[4]));
} else {
  tables = require('./generate_tables');
}

// ============================================================
// Helpers
// ============================================================

function toPascalCase(snake) {
  return snake.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function getAllColumns(table) {
  const cols = [
    `${table.name}_id`,
    ...table.columns.map(c => c.name),
    'modified',
    'created',
  ];
  if (table.needsShortId) {
    cols.push('short_id');
  }
  return cols;
}

function getTableDef(name) {
  return tables.find(t => t.name === name);
}

// ============================================================
// Data — loaded from stored_procedures_by.json
// ============================================================

const viewColumns = spByData.viewColumns;

// ============================================================
// _by_ list SP generator
// ============================================================

/**
 * Generate a _by_ list SP.
 *
 * @param {object} opts
 * @param {string} opts.spName - Full SP name
 * @param {string} opts.source - Table or view to query from
 * @param {string[]} opts.columns - Columns to SELECT
 * @param {string} opts.purpose - Description for header comment
 * @param {Array<{name, type, desc}>} opts.filterParams - Filter parameters
 * @param {string} opts.filterWhere - WHERE clause for filter (uses param names)
 * @param {Array<{name, type, desc, default}>} [opts.extraParams] - Extra params (date ranges etc.)
 */
function generateListBy(opts) {
  const {
    spName, source, columns, purpose,
    filterParams, filterWhere,
    extraParams = [],
  } = opts;

  const selectList = columns.map(c => `        ${c}`).join(',\n');
  const sortableCols = columns.map(c => `'${c}'`).join(', ');

  // Build parameter list
  const paramLines = [];
  for (const fp of filterParams) {
    paramLines.push(`    ${fp.name} ${fp.type}`);
  }
  for (const ep of extraParams) {
    const defaultStr = ep.default !== undefined ? ` = ${ep.default}` : '';
    paramLines.push(`    ${ep.name} ${ep.type}${defaultStr}`);
  }
  paramLines.push(`    @p_PageNumber INT = 1`);
  paramLines.push(`    @p_PageSize INT = 50`);
  paramLines.push(`    @p_SortBy NVARCHAR(50) = 'created'`);
  paramLines.push(`    @p_SortDirection NVARCHAR(4) = 'DESC'`);
  paramLines.push(`    @p_IncludeInactive BIT = 0`);

  // Build parameter docs
  const paramDocs = [];
  for (const fp of filterParams) {
    paramDocs.push(`    ${fp.name} ${fp.type} - ${fp.desc}`);
  }
  for (const ep of extraParams) {
    paramDocs.push(`    ${ep.name} ${ep.type} - ${ep.desc}`);
  }
  paramDocs.push(`    @p_PageNumber INT = 1 - Page number (1-based)`);
  paramDocs.push(`    @p_PageSize INT = 50 - Number of records per page`);
  paramDocs.push(`    @p_SortBy NVARCHAR(50) = 'created' - Column name to sort by`);
  paramDocs.push(`    @p_SortDirection NVARCHAR(4) = 'DESC' - Sort direction (ASC or DESC)`);
  paramDocs.push(`    @p_IncludeInactive BIT = 0 - If 1, include inactive records in results`);
  paramDocs.push(`    @o_RecordCount INT OUTPUT - Total number of matching records`);

  // Build extra WHERE conditions from extraParams (e.g., date ranges)
  let extraWhere = '';
  for (const ep of extraParams) {
    if (ep.whereClause) {
      extraWhere += `\n    AND ${ep.whereClause}`;
    }
  }

  // Build IF/ELSE IF branches for each column + direction combo
  const branches = [];
  for (const col of columns) {
    for (const dir of ['ASC', 'DESC']) {
      branches.push(`    ${branches.length === 0 ? 'IF' : 'ELSE IF'} @p_SortBy = '${col}' AND @p_SortDirection = '${dir}'
        SELECT
${selectList}
        FROM ${source}
        WHERE ${filterWhere}
        AND (is_active = 1 OR @p_IncludeInactive = 1)${extraWhere}
        ORDER BY ${col} ${dir}
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);
    }
  }
  // Default fallback (created DESC)
  branches.push(`    ELSE
        SELECT
${selectList}
        FROM ${source}
        WHERE ${filterWhere}
        AND (is_active = 1 OR @p_IncludeInactive = 1)${extraWhere}
        ORDER BY created DESC
        OFFSET (@p_PageNumber - 1) * @p_PageSize ROWS FETCH NEXT @p_PageSize ROWS ONLY;`);

  return `-- ABSOLUTELY DO NOT EDIT THIS FILE. IT WAS GENERATED BY generate_stored_procedures_by.js. DO NOT MODIFY OR REMOVE THIS COMMENT UNDER PENALTY OF CERTAIN DEATH.
SET QUOTED_IDENTIFIER ON;
GO
/*
=============================================================================
Procedure: ${spName}
Purpose: ${purpose}
Author: Generated
Created: 2026-02-22

Parameters:
${paramDocs.join('\n')}

Returns:
    Paged result set with sort and direction applied
    @o_RecordCount contains total matching records for paging UI
=============================================================================
*/
IF EXISTS (SELECT * FROM sys.procedures WHERE name = '${spName}')
    DROP PROCEDURE ${spName};
GO

CREATE PROCEDURE ${spName}
${paramLines.join(',\n')},
    @o_RecordCount INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    -- Validate sort parameters
    IF @p_SortBy NOT IN (${sortableCols})
        SET @p_SortBy = 'created';

    IF @p_SortDirection NOT IN ('ASC', 'DESC')
        SET @p_SortDirection = 'DESC';

    -- Total count
    SELECT @o_RecordCount = COUNT(*)
    FROM ${source}
    WHERE ${filterWhere}
    AND (is_active = 1 OR @p_IncludeInactive = 1)${extraWhere};

    -- Paged results (static ORDER BY per column to allow index usage)
${branches.join('\n')}

    SET NOCOUNT OFF;
END;
GO
`;
}

// ============================================================
// Build SP definitions from JSON data
// ============================================================

const spDefs = [];

// Resolve columns for an SP definition from JSON
function resolveColumns(def) {
  if (def.columnsFrom) {
    return viewColumns[def.columnsFrom];
  }
  if (def.columnsFromTable) {
    const tDef = getTableDef(def.columnsFromTable);
    return tDef ? getAllColumns(tDef) : null;
  }
  return def.columns;
}

// Load SP definitions from JSON
for (const def of spByData.spDefs) {
  const columns = resolveColumns(def);
  if (!columns) continue; // skip if table not found

  if (def.filterCol) {
    // Simple listBy-style definition
    const paramName = `@p_${toPascalCase(def.filterCol)}`;
    spDefs.push({
      spName: def.spName,
      source: def.source,
      columns,
      purpose: def.purpose,
      filterParams: [{ name: paramName, type: def.filterType, desc: `Filter by ${def.filterCol}` }],
      filterWhere: `${def.filterCol} = ${paramName}`,
    });
  } else {
    // Custom definition with explicit filterParams/filterWhere
    spDefs.push({
      spName: def.spName,
      source: def.source,
      columns,
      purpose: def.purpose,
      filterParams: def.filterParams || [],
      extraParams: def.extraParams,
      filterWhere: def.filterWhere,
    });
  }
}

// Note/Document _by_ parent SPs (dynamic — depends on table existence)
for (const parent of spByData.noteParents) {
  const tableName = `${parent}_note`;
  const tDef = getTableDef(tableName);
  if (!tDef) continue;
  const paramName = `@p_${toPascalCase(`${parent}_id`)}`;
  spDefs.push({
    spName: `sx_list_${parent}_note_by_${parent}`,
    source: tableName,
    columns: getAllColumns(tDef),
    purpose: `Retrieves ${tableName} records filtered by ${parent}`,
    filterParams: [{ name: paramName, type: 'UNIQUEIDENTIFIER', desc: `Filter by ${parent}_id` }],
    filterWhere: `${parent}_id = ${paramName}`,
  });
}

for (const parent of spByData.documentParents) {
  const tableName = `${parent}_document`;
  const tDef = getTableDef(tableName);
  if (!tDef) continue;
  const paramName = `@p_${toPascalCase(`${parent}_id`)}`;
  spDefs.push({
    spName: `sx_list_${parent}_document_by_${parent}`,
    source: tableName,
    columns: getAllColumns(tDef),
    purpose: `Retrieves ${tableName} records filtered by ${parent}`,
    filterParams: [{ name: paramName, type: 'UNIQUEIDENTIFIER', desc: `Filter by ${parent}_id` }],
    filterWhere: `${parent}_id = ${paramName}`,
  });
}

// ============================================================
// Write files
// ============================================================

if (isMain) {
  const outputBase = process.argv[3] ? path.resolve(process.argv[3]) : __dirname;
  const SP_DIR = path.join(outputBase, 'STORED_PROCEDURES');

  if (!fs.existsSync(SP_DIR)) {
    fs.mkdirSync(SP_DIR, { recursive: true });
  }

  let count = 0;

  for (const def of spDefs) {
    const sql = generateListBy(def);
    fs.writeFileSync(path.join(SP_DIR, `${def.spName}.sql`), sql, 'utf8');
    count++;
  }

  console.log(`Generated ${count} stored procedure files in ${SP_DIR}`);
}

module.exports = spDefs;
